apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: minio-operator
  template:
    metadata:
      labels:
        name: minio-operator
    spec:
      serviceAccountName: minio-operator
      containers:
        - name: minio-operator
          # Replace this with the built image name
          image: gcr.io/codelity-co/minio-operator:v0.1.0
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "minio-operator"
